// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFL-wlZr2N-9HYUlduHCByRpqoC8Vknws',
    appId: '1:168658855309:web:052912e7f88697138989c4',
    messagingSenderId: '168658855309',
    projectId: 'socialmedia-9b6dd',
    authDomain: 'socialmedia-9b6dd.firebaseapp.com',
    storageBucket: 'socialmedia-9b6dd.appspot.com',
    measurementId: 'G-DQK0EKKY27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzcJZedehQo4anNCYqWkLMuCkO4bbXi1g',
    appId: '1:168658855309:android:60a2f427137bf2078989c4',
    messagingSenderId: '168658855309',
    projectId: 'socialmedia-9b6dd',
    storageBucket: 'socialmedia-9b6dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALfbn5KBzeoOS4ZPW3-N9cI4pWc1B7h68',
    appId: '1:168658855309:ios:5a0398e1fba607268989c4',
    messagingSenderId: '168658855309',
    projectId: 'socialmedia-9b6dd',
    storageBucket: 'socialmedia-9b6dd.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALfbn5KBzeoOS4ZPW3-N9cI4pWc1B7h68',
    appId: '1:168658855309:ios:83079c1d77a78d828989c4',
    messagingSenderId: '168658855309',
    projectId: 'socialmedia-9b6dd',
    storageBucket: 'socialmedia-9b6dd.appspot.com',
    iosBundleId: 'com.example.socialMedia.RunnerTests',
  );
}
